travis:
  secure:
    BINSTAR_TOKEN: dKiACeFao7TXmyljy1EOj3JoArjcUtrweGfzikaROw16Ahq+eDb/4FK4CmOkNK0YJv9CEXn8+oAc9B8n1K6rWCZ4Kq35ei71jjBP6deCyl++d25rm3M81Fu4DRufFGwG+3qo74vdpCedFPKo6l4AxfWJSqeXagh1TGRFvUtboSLqAiPlCERekUurVquCwNEBMD8lyYV2ne96TVurNMvnNlPwqSoo4mdvjkwkmAREO2oAvGutIvur+VoC91Z25AR9VESslZsqBKefNFGRbmo1OWC2VYK8UeihL9GeTzod2B8YZ0/lch9tTNzYsLyuATY8O10vaeyrGd7VAY84iEYcHBSh/z+wbkkkdhgyQaEQNR9ADcQAybPP9uqjmBd63Gvtn/PPkyRrz3QuKJhj+aXnFh4p/jFYQCyzJjI8a/QflZzS/uUz1jC4Lkg/snU2tnYyW06CAp9YXKIwKmZsiJhM3gARL7+zNv8yDM9GkM2+ryVOfqrRr3gCtIyRKr1TDLmF6DG8w18FhFeARyfk6QSF0G+MimGlsmr3XdsP52Ldx1scRNNocJwO5Aji4EvcOZYY0BeD8OPYO42geRQn86YmDdCP0s50/UP1b1sJRrILuZdimig+X4uPUyetJjeilafpQa+9N6rGOTmff6w8OSeXn3W6jJoSxmVz+WpoGOKahBY=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
