travis:
  secure:
    BINSTAR_TOKEN: bq2IZ9X10lqfCPHtezOkMCf65fgwXIvxQ9+tjCjfrjOiBzTHBJ0qtjy90xaBnE/G3GyuVnfFMJ327qQnYvXddf4dLmnmzv2lArDHzgFoZl3Ee2ow5YqvawTWKWOf1Jdq6Xi59Huk8+OeoIwdHf5+19kGHlb08hTfLCIId9vWLgsus3gkqFo1IcYKNrmZsG2KXRLd77gkU9KCJnFR/i1sBhLUkJQgQFLRIVBeu/N/5A8JHsh1ejw/iKQUhPZziAo1CTa45XJzCUklguxMpfHmCCIrso1KHl1Bi/wLGy6tvdEAlKGza3H5LbxDhQEGr79x+21y9K8otlNI6VVRQEiApZG7VogUDzBcJrOPW2vlAqvmFDyLjduumwbgttKuXwlAgiHaPLMgfXWdafUyhiDUZMSibGcYXYpf5/jWIKcx0uKfT/7V+hQavvrYQf0J/vq1irrhWgzYn15IIx+qhqXvWJnhzs8kSu3XF96P9qSE0TH+bmwxYL1Nkpp9zwiwZ+trgR+k/GtSCSjXmpi4W+K5AZTgMaKmSAk1aXKOsHWrW8N7gNeF119LfRllrZNoikke6zh+ptvXShx4Fip8aTOj1OzkAHxZ8z4WVO+TwA1C+zZYfHA3HEY3rKFiAVIuAp4gizKDBpWoar2ziJL0WwEviyunF8kLjyalT9fq82td+1Q=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
